//exceptions

try{
    console.log(num);
}catch(error){
    console.log("Error is: "+error);
}finally{
    console.log("Anyway lets continue executing")
}